version: "2"
services:
  node:
    image: "reedcrif/docker-jwtbuilder"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    ports:
      - 3000:3000
    command: "npm start"
